name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: daehyeong2010/sh4re
          stage: main
          yaml: >
            name: sh4re-web

            app: dockerfile

            options:
              ports: "8080"
              dockerfile: Dockerfile
              env: []
              args:
                - name: VITE_BACKEND_URL
                  value: https://port-0-sh4re-server-malnu3or6bb092b3.sel4.cloudtype.app
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: dockerfile